sudo: true
language: haskell

git:
  depth: 5

cabal: "head"

cache:
  directories:
  - "$HOME/.cabal/store"

matrix:
  include:
  - ghc: 8.6.3


install:
  - cabal new-update
  - cabal new-build --enable-tests --enable-benchmarks

script:
  - curl -sSL https://raw.github.com/ndmitchell/neil/master/misc/travis.sh | sh -s -- hlint .

notifications:
  email: false
